version: "3.9"

services:
  web:
    build: .
    command: python /code2/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code2
    ports:
      - 8000:8000
    depends_on:
      - db  

     
    
  db:
   image: postgres:13.4-alpine
   restart: always
   volumes: 
     - postgres_data:/var/lib/postgresql/data/
   environment:
     - "POSTGRES_HOST_AUTH_METHOD=trust"
    #  - POSTGRES_PASSWORD=postgres
     
volumes:
  postgres_data: